#!/bin/bash

# BeeQuiet | 1Password Secrets
# 
# Example:
#  ./getSecrets.sh
#  ./getSecrets.sh beehive

INVOKING_USER="${USER:-${SUDO_USER:-root}}"

set -e

# ----- Colors -----

RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m'

VAULT_NAME="TekKom Dev"

print_info()    { echo -e "${BLUE}ℹ️  $1${NC}"; }
print_success() { echo -e "${GREEN}✅  $1${NC}"; }
print_warning() { echo -e "${YELLOW}⚠️  $1${NC}"; }
print_error()   { echo -e "${RED}❌  $1${NC}"; }

# ----- Fetches secrets -----

fetch_env_from_item() {
    local item="$1"
    local output_path="$2"

    mkdir -p "$(dirname "$output_path")"

    local item_json
    item_json=$(op item get "$item" --vault="$VAULT_NAME" --format json 2>/dev/null || echo "")

    local content=""
    if [[ -n "$item_json" && "$item_json" != "null" ]]; then
        content=$(echo "$item_json" | jq -r '.fields[] | select(.value and .value != "") | if (.label | test("notesPlain"; "i")) then (.value | split("\n") | map(select(. != "" and (. | test("="))) | split("=") | {k: .[0] | ascii_upcase | gsub(" "; "_") | gsub("[^A-Z0-9_]"; ""), v: .[1:] | join("=")} | select(.k != "") | "\(.k)=\"\(.v | gsub("\""; "\\\""))\"") | join("\n") else (.label | ascii_upcase | gsub(" "; "_") | gsub("[^A-Z0-9_]"; "") as $key | select($key != "") | "\($key)=\"\(.value | gsub("\""; "\\\""))\"" end)' 2>/dev/null || echo "")
        if [[ -z "$content" ]]; then
            local notes_plain
            notes_plain=$(echo "$item_json" | jq -r '.notesPlain // empty' 2>/dev/null || echo "")
            if [[ -n "$notes_plain" ]]; then
                local key
                key=$(echo "$item" | tr '[:lower:]' '[:upper:]' | sed 's/[^A-Z0-9_]/_/g')
                content="$key=\"$(echo "$notes_plain" | sed 's/"/\\"/g')\""
            fi
        fi
    fi

    if [[ -n "$content" ]]; then
        echo "# Generated by BeeQuiet on $(date)" > "$output_path"
        echo "# Source: 1Password vault='$VAULT_NAME' item='$item'" >> "$output_path"
        echo "" >> "$output_path"
        echo "$content" >> "$output_path"
        chmod 600 "$output_path"
        print_success "Saved to $output_path"
    else
        print_error "No valid fields found in item '$item'"
    fi
}

# ----- Main -----

main() {
    # Checks if op CLI is installed
    if ! command -v op &> /dev/null; then
        print_error "1Password CLI (op) is not installed."
        exit 1
    fi

    # Checks if jq is installed
    if ! command -v jq &> /dev/null; then
        print_error "jq is not installed."
        exit 1
    fi

    # Checks if signed in
    if ! op account get &> /dev/null; then
        print_error "Not signed in to 1Password."
        exit 1
    fi

    local path="${1:-$(basename "$PWD")}"
    local item="${path}_secrets"
    local output_path="/home/$INVOKING_USER/$path/.env"

    fetch_env_from_item "$item" "$output_path"
}

main "$@"
